language: python
python: 
 - "2.7"

install: 
 - pip install tox
 - pip install flake8-diff
script:
 - git fetch origin $TRAVIS_BRANCH:travis_pr_branch
 - flake8-diff travis_pr_branch
 - cd core && tox -e $TOXENV_CORE
env:
 - TOXENV_CORE=py27
