---
  - name: Include tasks for master.
    include: master.yml
    when: "'master' in group_names"
    tags:
      - master

  - name: Create users for each application.
    include: users.yml
    when: "'slaves' in group_names"

  - name: Include common tasks.
    include: common-1.yml

  - name: Include more common tasks.
    include: common-2.yml
