---
  - name: Install apache2, apache2-dev and libapache2-mod-wsgi packages.
    apt: name={{ item }} state=latest
    with_items:
      - apache2
      - apache2-dev
      - libapache2-mod-wsgi

  - name: Get the hostname of the vm.
    command: hostname
    register: hostname

  - name: Copy Lambda sites-available backend configuration.
    template: src=lambda-service-backend.conf.j2 dest=/etc/apache2/sites-available/lambda-service-backend.conf

  - name: Copy lambda sites-available frontend configuration.
    template: src=lambda-service-frontend.conf.j2 dest=/etc/apache2/sites-available/lambda-service-frontend.conf

  - name: Add lambda-service-backend to sites-enabled.
    command: a2ensite lambda-service-backend.conf

  - name: Add lambda-service-frontend to sites-enabled.
    command: a2ensite lambda-service-frontend.conf

  - name: Remove default sites-enabled.
    command: a2dissite 000-default.conf

  - name: Activate Apache rewrite module.
    apache2_module: name=rewrite state=present
    notify:
          - restart_apache2

  - name: Activate Apache headers module.
    apache2_module: name=headers state=present
    notify:
          - restart_apache2

  - name: Configure Apache.
    lineinfile: dest=/etc/apache2/apache2.conf line="WSGIPythonPath {{ repository_download_path }}/okeanos-LoD/webapp" state=present insertafter=EOF
    notify:
      - restart_apache2
