---
  - name: Download Apache Flink, Yarn version.
    get_url: url="{{ mirror_url }}/flink-{{ version }}/flink-{{ version }}-{{ version_for }}.tgz" dest="{{ download_path }}/flink-{{ version }}-{{ version_for }}.tgz"
    environment: proxy_env 
    tags:
      - download

  - name: Uncompress Apache Flink.
    unarchive: src="{{ download_path }}/flink-{{ version }}-{{ version_for }}.tgz" dest="{{ installation_path }}" copy=no owner=flink group=lambda
    tags:
      - uncompress

  - name: Create softlink for Apache Flink.
    file: src="{{ installation_path }}/flink-{{ version }}" dest="{{ installation_path }}/flink" state=link
    tags:
      - uncompress

  - name: Configure Apache Flink.
    template: src=flink-conf.j2 dest="{{ installation_path }}/flink/conf/flink-conf.yaml" owner=flink group=lambda mode=0644
    tags:
      - configure

  - name: Copy Apache Flink init script.
    template: src=flink-init.j2 dest=/etc/init.d/flink-init owner=flink group=lambda mode=0740

  - name: Start Apache Flink.
    shell: /etc/init.d/flink-init start > /dev/null
    tags:
      - start

